[2025-02-01 22:13:58] [INFO    ] discord.client: logging in using static token
[2025-02-01 22:13:59] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 4885ca6ac3abc1914b7c0db55b8f911c).
[2025-02-01 22:14:31] [INFO    ] discord.voice_state: Connecting to voice...
[2025-02-01 22:14:31] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2025-02-01 22:14:31] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: rotterdam7930.discord.media
[2025-02-01 22:14:31] [INFO    ] discord.voice_state: Voice connection complete.
[2025-02-01 22:14:39] [INFO    ] discord.voice_state: Disconnected from voice by force... potentially reconnecting.
[2025-02-01 22:14:39] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1328821698476249190 (Guild ID 779447967433883699)
[2025-02-01 22:14:39] [INFO    ] discord.voice_state: Reconnect was unsuccessful, disconnecting from voice normally...
[2025-02-01 22:14:39] [INFO    ] discord.player: ffmpeg process 14251 has not terminated. Waiting to terminate...
[2025-02-01 22:14:39] [INFO    ] discord.player: ffmpeg process 14251 should have terminated with a return code of -9.
[2025-02-01 22:14:42] [ERROR   ] asyncio: Task exception was never retrieved
future: <Task finished name='Task-21' coro=<MusicQuiz.start_song() done, defined at /home/tagordo/Documents/side-projects/music-quiz-bot/bot/cogs/musicQuiz.py:186> exception=AttributeError("'NoneType' object has no attribute 'play'")>
Traceback (most recent call last):
  File "/home/tagordo/Documents/side-projects/music-quiz-bot/bot/cogs/musicQuiz.py", line 194, in start_song
    await self.play_audio_url(ctx, audio_url)
  File "/home/tagordo/Documents/side-projects/music-quiz-bot/bot/cogs/musicHandler.py", line 81, in play_audio_url
    voice_client.play(source,after=partial(self.next_song, ctx=ctx))
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'play'
[2025-02-01 22:14:42] [INFO    ] discord.player: ffmpeg process 14330 has not terminated. Waiting to terminate...
[2025-02-01 22:14:42] [INFO    ] discord.player: ffmpeg process 14330 should have terminated with a return code of -9.
[2025-02-01 22:15:15] [INFO    ] discord.voice_state: Connecting to voice...
[2025-02-01 22:15:15] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2025-02-01 22:15:15] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: rotterdam7930.discord.media
[2025-02-01 22:15:15] [INFO    ] discord.voice_state: Voice connection complete.
[2025-02-01 22:15:24] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1328821698476249190 (Guild ID 779447967433883699)
[2025-02-01 22:15:24] [INFO    ] discord.player: ffmpeg process 14615 has not terminated. Waiting to terminate...
[2025-02-01 22:15:24] [INFO    ] discord.player: ffmpeg process 14615 should have terminated with a return code of -9.
[2025-02-01 22:15:27] [ERROR   ] asyncio: Task exception was never retrieved
future: <Task finished name='Task-42' coro=<MusicQuiz.start_song() done, defined at /home/tagordo/Documents/side-projects/music-quiz-bot/bot/cogs/musicQuiz.py:186> exception=AttributeError("'NoneType' object has no attribute 'play'")>
Traceback (most recent call last):
  File "/home/tagordo/Documents/side-projects/music-quiz-bot/bot/cogs/musicQuiz.py", line 194, in start_song
    await self.play_audio_url(ctx, audio_url)
  File "/home/tagordo/Documents/side-projects/music-quiz-bot/bot/cogs/musicHandler.py", line 81, in play_audio_url
    voice_client.play(source,after=partial(self.next_song, ctx=ctx))
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'play'
[2025-02-01 22:15:27] [INFO    ] discord.player: ffmpeg process 14708 has not terminated. Waiting to terminate...
[2025-02-01 22:15:27] [INFO    ] discord.player: ffmpeg process 14708 should have terminated with a return code of -9.
[2025-02-01 22:15:27] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/tagordo/snap/code/179/.local/share/virtualenvs/music-quiz-bot-PZw_aL80/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/home/tagordo/Documents/side-projects/music-quiz-bot/bot/cogs/musicQuiz.py", line 117, in on_message
    if self.game['artist_guessed'] and self.game['song_guessed']:
       ~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'artist_guessed'
[2025-02-01 22:15:41] [INFO    ] discord.voice_state: Connecting to voice...
[2025-02-01 22:15:41] [INFO    ] discord.voice_state: Starting voice handshake... (connection attempt 1)
[2025-02-01 22:15:42] [INFO    ] discord.voice_state: Voice handshake complete. Endpoint found: rotterdam7930.discord.media
[2025-02-01 22:15:42] [INFO    ] discord.voice_state: Voice connection complete.
[2025-02-01 22:15:50] [INFO    ] discord.voice_state: The voice handshake is being terminated for Channel ID 1328821698476249190 (Guild ID 779447967433883699)
[2025-02-01 22:15:50] [INFO    ] discord.player: ffmpeg process 14864 has not terminated. Waiting to terminate...
[2025-02-01 22:15:50] [INFO    ] discord.player: ffmpeg process 14864 should have terminated with a return code of -9.
